fix(shortcuts): always unregister global shortcuts before reregistering Fixes an error where I was getting
```
TypeError: window['_3282349814'] is not a function. (In 'window['_3282349814']({ message: {"shortcut":"shift+super+KeyD","id":570425366,"state":"Pressed"}, index: 14 })', 'window['_3282349814']' is undefined)
```

since the old callback registered was somehow being lost on full page refreshes. Unregistering before reregistering fixes this.


Former-commit-id: ba7bbca4916a165606e93d644b3d8e18c81b0019
Former-commit-id: 5bffd88aa66e52cf622e52bd7a73fb529a54ebbd